#!/usr/bin/env python3
import os
import sys

try:
    from PIL import Image
except ImportError:
    print("PIL not available, trying to install...")
    os.system("pip install Pillow")
    from PIL import Image

def analyze_png_metadata(image_path):
    """Extract metadata from PNG files generated by Stable Diffusion"""
    try:
        img = Image.open(image_path)
        print(f"\nAnalyzing: {os.path.basename(image_path)}")
        print(f"Size: {img.size}")
        print(f"Mode: {img.mode}")
        
        print("\nPNG Info keys:", list(img.info.keys()))
        
        # Look for common Stable Diffusion metadata keys
        metadata_keys = ['parameters', 'prompt', 'negative_prompt', 'seed', 'steps', 'cfg_scale']
        
        for key in metadata_keys:
            if key in img.info:
                print(f"{key}: {img.info[key]}")
        
        # Print all metadata if parameters key exists
        if 'parameters' in img.info:
            print("\nFull parameters:")
            print(img.info['parameters'])
            
        return img.info
        
    except Exception as e:
        print(f"Error analyzing {image_path}: {e}")
        return None

if __name__ == "__main__":
    # Analyze a few sample images
    sample_images = [
        "../projx/fmg/attack on titan/mikasa/00001-1137014919.png",
        "../projx/fmg/bleach/orihime/00000-3787653981.png",
        "../projx/fmg/final fantasy/tifa/00001-3830150927.png"
    ]
    
    for img_path in sample_images:
        if os.path.exists(img_path):
            analyze_png_metadata(img_path)
        else:
            print(f"File not found: {img_path}")